### ISSUE TITLE
Compile utils/Koans.ex fails with Elixir 1.0.0

### ISSUE THREAD

**Issue by ovhaag** [dojo-toulouse/elixir-koans#15]
`$ elixirc utils/Koans.ex` gives:

== Compilation error on file utils/Koans.ex ==
** (CompileError) utils/Koans.ex:2: undefined function defexception/3
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (elixir) src/elixir_exp.erl:49: :elixir_exp.expand/2
    (elixir) src/elixir.erl:206: :elixir.quoted_to_erl/3
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3

I use Elixir 1.0.0, installed with homebrew on OS X. And the installation seems to be ok. (No error and no warning on installation. And on my first steps in elixir everything worked fine.)

**Comment by Kazark** [comment]
I'm getting this too for Elixir 1.0.2

**Comment by apieum** [comment]
Yes I wrote this months ago to play with elixir and now don't have the time to maintain it. If you have a patch I would greatly appreciate. ;)

**Comment by Kazark** [comment]
Thanks! That seems to have fixed the one error for me, though I am now encountering something else. If I get a chance, I'll look more into it.

**Comment by apieum** [comment]
Hope you'll not. 
Thanks all for reporting the issue, and Ignu for your patch.
