### ISSUE TITLE
Issue in "Assertions are smart"

### ISSUE THREAD

**Issue by MarcosX** [dojo-toulouse/elixir-koans#19]
Hi all, I'm pretty new to Elixir and using this Koans to learn more about the language and I stumbled on the following issue (while meditating about "Assertions are smart"):

* The `assert` function doesn't seem to be raising a `ExUnit.ExpectationError` anymore, instead it's raising a `ExUnit.AssertionError`.
* The error message also seems to be different, it used to be `"Expected 1 to be equal to 2"` but now it is `"Assertion with == failed"`

Here is an example of changes I've made in my local copy

```elixir
    think "Assertions are smart" do
        is_1_equal_2? = fn -> assert 1 == 2 end
        is_1_greater_than_2? = fn -> assert 1 > 2 end

        #This works:
        message = "Assertion with " <> "==" <> " failed"
        assert_raise ExUnit.AssertionError, message, is_1_equal_2?

        #This doesn't:
        message = "Expected 1 to be " <> __? <> " 2"
        assert_raise ExUnit.ExpectationError, message, is_1_greater_than_2?
    end
```

Looking at the code for version 1.0.4 (which is what I have now), it seems like we might need to update.

```elixir
  def assert(value, message) when is_binary(message) do
    assert(value, message: message)
  end

  def assert(value, opts) when is_list(opts) do
    unless value, do: raise(ExUnit.AssertionError, opts)
    true
  end
```
from https://github.com/elixir-
lang/elixir/blob/a3dd9e247375bd99dbac115cdd6d11f08d71952f/lib/ex_unit/lib/ex_unit/assertions.ex

Let me know what you all think and I can make a PR if needed :)

**Comment by apieum** [comment]
Hi, thank you.
I've made these koans for one dojo to test elixir, then I've never had the time to improve and maintain it or develop something else with elixir. 
Others have done, but probably you're going to find bugs as I accept PR without testing them and because elixir has evolved a lot since our dojo.

Your code seems good, just don't forget to replace "==" by __?
