### ISSUE TITLE
Can not start: "(Koans.MeditateWarning) Please meditate: you should start a ExUnit server to automatically run your test case"

### ISSUE THREAD

**Issue by phanimahesh** [dojo-toulouse/elixir-koans#21]
I am fairly new to Elixir so I might be missing something obvious, but I can not start any koan from the repository.
```sh
$ elixirc utils/Koans.ex
$ ./path_to_enlightenment.exs
utils/Koans.ex:1: warning: redefining module Koans.MeditateWarning
utils/Koans.ex:9: warning: redefining module Koans
utils/Koans.ex:43: warning: redefining module Koans.About_testing
utils/Koans.ex:70: warning: redefining module FakeUnit.Case
** (Koans.MeditateWarning) Please meditate: you should start a ExUnit server to automatically run your test case
    utils/Koans.ex:30: Koans.meditate/1
    about_testing.exs:3: (file)
    (elixir) lib/code.ex:278: Code.load_file/2
    path_to_enlightenment.exs:5: (file)
```

**Comment by apieum** [comment]
Hi, of course, it's koans: an exercise to understand basic features about elixir. 
You have to replace "__" by values in tests files. Meditate Warning indicate the place where you've to change the code and what you've to do.

**Comment by phanimahesh** [comment]
Oh, makes sense. I didn't know what a koan meant, just looked it up. :P

**Comment by apieum** [comment]
I think the term [koan](https://en.wikipedia.org/wiki/K%C5%8Dan) was first coined in [ruby](http://rubykoans.com). 
We've not pushed the logic too much here, it's just small exercises to discover few features of elixir. In fact I started to wrote it for an informal workshop with friends to discover elixir, just in case to have a support, so it is far to be finished and it is maintained just the minimum.
