### ISSUE TITLE
is koans the right word ?

### ISSUE THREAD

**Issue by apieum** [dojo-toulouse/elixir-koans#27]
When I've started it, it was just a background to play with friends in the *koans way*.
I think it is more a tour on elixir than a real exercise that emphasize the way of thinking in elixir and I don't want to induce errors in people minds with an inappropriate term.

I suggest to rename the repository **elixir-tour**.

Any objection ?

**Comment by cmpaul** [comment]
I found the repo by searching for "elixir koans" so it might affect discoverability. Maybe you could adjust the approach in a way that makes it more *koans*-like?

**Comment by apieum** [comment]
Thank you, and sorry I'm curious.
Were you satisfied to find this repo when you've searched "elixir koans" ?

**Comment by cmpaul** [comment]
@apieum To be honest, I've only spent about 15 minutes with it and have only completed the first two scripts (about_anonymous_function.exs and about_testing.exs), but yes, I'm satisfied so far. I'll reply with more feedback once I've had time to complete it.

**Comment by apieum** [comment]
OK one person is enough I close this. :)
