### ISSUE TITLE
Code indent style violates published conventions

### ISSUE THREAD

**Issue by moxley** [dojo-toulouse/elixir-koans#36]
One of the first things I noticed when trying out these Koans is that the code is formatted with 4-space indentations rather than 2 spaces.

Here are the first three Elixir style guides returned from a Google search for "elixir code style guide". All three guides recommend or require 2-space indents.

https://github.com/niftyn8/elixir_style_guide#source-code-layout
https://github.com/rrrene/elixir-style-guide#code-readability
https://github.com/lexmag/elixir-style-guide#source-code-layout

I could reformat the source files if you'd like, but I wanted to run this by you first.

**Comment by apieum** [comment]
hi, there is no authoritative style guide for elixir. :)

http://stackoverflow.com/questions/30772254/does-elixir-have-coding-standards-or-an-authoritative-style-guide-published-by-t
